// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPexHJP0j9EArRWKPDbZecvkjBQsZxD6I',
    appId: '1:382565316027:web:e052b813549479c539c09e',
    messagingSenderId: '382565316027',
    projectId: 'airqualitymonitoringsyst-6c370',
    authDomain: 'airqualitymonitoringsyst-6c370.firebaseapp.com',
    databaseURL: 'https://airqualitymonitoringsyst-6c370-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'airqualitymonitoringsyst-6c370.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFu3abNeZ94E33U4vIg2yYD0hmo9jfIVY',
    appId: '1:382565316027:android:ee9605d2d8706a6139c09e',
    messagingSenderId: '382565316027',
    projectId: 'airqualitymonitoringsyst-6c370',
    databaseURL: 'https://airqualitymonitoringsyst-6c370-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'airqualitymonitoringsyst-6c370.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA76FJT7dXUeSuNkaT25WBgukx56eW_U8c',
    appId: '1:382565316027:ios:aa3edd8935d8d13039c09e',
    messagingSenderId: '382565316027',
    projectId: 'airqualitymonitoringsyst-6c370',
    databaseURL: 'https://airqualitymonitoringsyst-6c370-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'airqualitymonitoringsyst-6c370.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA76FJT7dXUeSuNkaT25WBgukx56eW_U8c',
    appId: '1:382565316027:ios:aa3edd8935d8d13039c09e',
    messagingSenderId: '382565316027',
    projectId: 'airqualitymonitoringsyst-6c370',
    databaseURL: 'https://airqualitymonitoringsyst-6c370-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'airqualitymonitoringsyst-6c370.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPexHJP0j9EArRWKPDbZecvkjBQsZxD6I',
    appId: '1:382565316027:web:9a1f79bf0625911839c09e',
    messagingSenderId: '382565316027',
    projectId: 'airqualitymonitoringsyst-6c370',
    authDomain: 'airqualitymonitoringsyst-6c370.firebaseapp.com',
    databaseURL: 'https://airqualitymonitoringsyst-6c370-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'airqualitymonitoringsyst-6c370.firebasestorage.app',
  );

}